error: refactor common hint-pattern into a common base class
I'm about to make another exception class require hints, so third
strike and you refactor.